### ISSUE TITLE
https://grails.org/single-page-documentation.html does not scroll on OSX Safari (9.0.3)

### ISSUE THREAD

**Issue by ben3000** [grails/grails-static-website#35]
The above-mentioned part of the grails website doesn't scroll with the mouse on Safari. It works perfectly with Firefox (44.0).

**Comment by vonovak** [comment]
My pull request that was recently merged tried to solve the trouble with two vertical sliders that were showing up on the [documentation page](https://grails.org/single-page-documentation.html). Can you verify if it works with safari now? Since I'm running ubuntu I have no quick way of checking this...

**Comment by ben3000** [comment]
Yep, that seems to have fixed the issue, ta.

**Comment by graemerocher** [comment]
Thanks @vonovak !
